server:
  shutdown: graceful

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clush_assignment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jwjw0185**

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true